create table if not exists table_list(_id integer primary key autoIncrement,table_num text,table_name text,table_add text,table_size text,staff_num text)
create table if not exists dish_list(_id integer primary key autoIncrement,dish_id text,dish_name text,price text,introduction text,dish_class text,dish_unit text,img_path text,load_position text default 0,img_download boolean default 0)
create table if not exists temp_orders(_id integer primary key autoIncrement,table_num text,dish_id text,count text default 1,remark text default '')
create table if not exists orders(_id integer primary key autoIncrement,order_id text,table_num text,checkout boolean default 0)

insert into table_list(table_num,table_name,table_size) values('101','一楼1桌',4)
insert into table_list(table_num,table_name,table_size) values('102','一楼2桌',6)
insert into table_list(table_num,table_name,table_size) values('103','一楼3桌',6)
insert into table_list(table_num,table_name,table_size) values('104','一楼4桌',8)
insert into table_list(table_num,table_name,table_size) values('201','二楼1桌',10)
insert into table_list(table_num,table_name,table_size) values('202','二楼2桌',6)
insert into table_list(table_num,table_name,table_size) values('301','三楼1桌',10)
insert into table_list(table_num,table_name,table_size) values('302','三楼2桌',20)
insert into table_list(table_num,table_name,table_size) values('303','三楼3桌',12)

insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('1','辣炒么锦藕丁','52/份','干煸是川菜中相当普遍的一种做法.是把食材用油慢慢煸干而衍生出一种特别的滑嫩腴香，清新爽口','热菜',1,'images/recai1.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('2','私房东波肉','85/份','这是一道色泽好看，鱼质鲜嫩的家常菜。而且鲈鱼本身就有营养，味道鲜','热菜',1,'images/recai2.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('3','红烧排骨','62/份','可乐鸡翅是一道常见的家常美味菜肴。有许多种做法，但主料均味鸡翅和可乐。其成菜味道鲜美，色泽艳丽，鸡翅嫩滑，又保留了可乐的香气','热菜',1,'images/recai3.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('4','宫保鸡丁','52/份','豆腐的营养丰富，是家庭炒菜中广泛使用的材料。豆腐的做法很多，南北方各异，味道有清淡、有浓郁，亦可凉拌、烧煮、做汤','热菜',1,'images/recai4.png')

insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('5','自煎一面黄','35/份','肉皮冻富含丰富的胶原蛋白，不但韧性好、口感佳，而且对人的皮肤、筋腱、骨骼、毛发都有重要的生理保健作用，物美价廉，美容养颜效果极好，是女士们不可多得的美容佳品。菠菜富含维生素 C、胡萝卜素、蛋白质，以及铁、钙、磷等矿物质。两者结合成双色的肉皮冻，再搭成魔方的形状，好吃又好看','凉菜',1,'images/liangcai1.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('6','西蓝花拌虾仁','42/份','金针菇营养丰富。有益智的功效。这道葱油金针菇口感非常开胃爽口，是一道非常有代表性的凉菜','凉菜',1,'images/liangcai2.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('7','中式辣萝卜','25/份','这是一个东南亚菜它的特色在于：黄红相间，浓香味醇。喜欢咖喱的朋友别错过','凉菜',1,'images/liangcai3.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('8','冰糖糯米藕','45/份','猪肝中铁质丰富，是补血食品中最常用的食物，食用猪肝可调节和改善贫血病人造血系统的生理功能；能保护眼睛，维持正常视力，防止眼睛干涩、疲劳，维持健康的肤色，对皮肤的健美具有重要意义；经常食用动物肝还能补充维生素B2，这对补充机体重要的辅酶，完成机体对一些有毒成分的去毒有重要作用；猪肝中还具有一般肉类食品不含的维生素Ｃ和微量元素硒，能增强人体的免疫反应，抗氧化，防衰老，并能抑制肿瘤细胞的产生，也可治急性','凉菜',1,'images/liangcai4.png')

insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('9','四神汤','20/份','这个汤，非常鲜甜好喝，加了赤小豆和眉豆，还有祛湿的效果','汤类',1,'images/tanglei1.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('10','暖身黑鱼汤','32/份','这个汤，非常鲜甜好喝，加了赤小豆和眉豆，还有祛湿的效果','汤类',1,'images/tanglei2.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('11','冬瓜鸡架汤','45/份','简单，功效却不可小觑，它可以使清肠排毒变得事半功倍。味道清淡的豆腐与滋味鲜美的海带可谓相得益彰的绝配，注重健康的人，会视这道汤为长生不老的妙药','汤类',1,'images/tanglei3.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('12','香菇豆腐汤','58/份','荸荠是寒性食物，有清热泻火的良好功效。既可清热生津，又可补充营养，最宜用于发烧病人。它具有凉血解毒、利尿通便、化湿祛痰、消食除胀等功效。在呼吸道传染病流行季节，吃马蹄有利于流脑、麻疹、百日咳及急性咽喉炎的防治','汤类',1,'images/tanglei4.png')

insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('13','夏日倾情套餐','38/套','可以迅速补充能量，又不会令人发胖，还有美容养颜的功效，特别适合爱美的女士','饮料',1,'images/yinliao1.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('14','清爽夏日套餐','26/套','可口可乐，来自美国，碳酸饮料，深受小朋友的喜爱','饮料',1,'images/yinliao2.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('15','蜜汁双皮奶','15/杯','柠檬薏米水是款美白养颜的健康饮料，特别受年轻女士的喜爱，薏米有清热利尿、去水肿、排毒的功效，柠檬酸可防止和消除皮肤色素沉着，并有滋润美白肌肤的作用，还可以防止电脑辐射。这两者合二为一美白功效可见一斑。','饮料',1,'images/yinliao3.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('16','温馨全家套餐','88/套','酸酸甜甜还有果粒的橘汁，既健康又经济','饮料',1,'images/yinliao4.png')


insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('21','软盒大华','38/包','中国人吃饭必备的餐具','其他',1,'images/qita1.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('21','硬盒白沙烟','13/包','中国人吃饭必备的餐具','其他',1,'images/qita2.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('21','硬盒红金圣','15/包','中国人吃饭必备的餐具','其他',1,'images/qita3.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('21','经典硬盒利群','88/包','中国人吃饭必备的餐具','其他',1,'images/qita4.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('21','软盒黄双喜','10/包','中国人吃饭必备的餐具','其他',1,'images/qita5.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('21','蓝色硬盒芙蓉王','25/包','中国人吃饭必备的餐具','其他',1,'images/qita6.png')


insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('00001','肉末茄子煲','42/份','溜虾仁溜虾仁溜虾仁','热菜',1,'images/recai5.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('00002','麻婆豆腐','38/份','松鼠桂鱼松鼠桂鱼','热菜',1,'images/recai6.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('00003','水煮龙虾','35/份','鱼香肉丝鱼香肉丝','热菜',1,'images/recai7.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('00004','么锦鸡柳','32/份','蓝莓香芋蓝莓香芋','热菜',1,'images/recai8.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('00005','香味牛肉','48/份','糖醋排骨糖醋排骨','热菜',1,'images/recai9.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('00006','华南鲤鱼','55/份','吊炉烤鸭吊炉烤鸭','热菜',1,'images/recai10.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('00007','香甜虾仁','48/份','吊炉烤鸭吊炉烤鸭','热菜',1,'images/recai11.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('00008','香辣茄子肉末','30/份','吊炉烤鸭吊炉烤鸭','热菜',1,'images/recai12.png')

insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('7','口水鸡','68/份','这是一个东南亚菜它的特色在于：黄红相间，浓香味醇。喜欢咖喱的朋友别错过','凉菜',1,'images/liangcai5.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('7','皮蛋豆腐','32/份','这是一个东南亚菜它的特色在于：黄红相间，浓香味醇。喜欢咖喱的朋友别错过','凉菜',1,'images/liangcai6.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('7','辣酱凉瓜','25/份','这是一个东南亚菜它的特色在于：黄红相间，浓香味醇。喜欢咖喱的朋友别错过','凉菜',1,'images/liangcai7.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('7','糖醋皮粉','15/份','这是一个东南亚菜它的特色在于：黄红相间，浓香味醇。喜欢咖喱的朋友别错过','凉菜',1,'images/liangcai8.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('7','么锦鸡蛋','20/份','这是一个东南亚菜它的特色在于：黄红相间，浓香味醇。喜欢咖喱的朋友别错过','凉菜',1,'images/liangcai9.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('7','香辣回锅肉','25/份','这是一个东南亚菜它的特色在于：黄红相间，浓香味醇。喜欢咖喱的朋友别错过','凉菜',1,'images/liangcai10.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('7','香味腊肉','35/份','这是一个东南亚菜它的特色在于：黄红相间，浓香味醇。喜欢咖喱的朋友别错过','凉菜',1,'images/liangcai11.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('7','金针菇拌海带','25/份','这是一个东南亚菜它的特色在于：黄红相间，浓香味醇。喜欢咖喱的朋友别错过','凉菜',1,'images/liangcai12.png')

insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('10','咖喱牛肉粉丝汤','45/份','这个汤，非常鲜甜好喝，加了赤小豆和眉豆，还有祛湿的效果','汤类',1,'images/tanglei5.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('10','茶树菇土鸡汤','35/份','这个汤，非常鲜甜好喝，加了赤小豆和眉豆，还有祛湿的效果','汤类',1,'images/tanglei6.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('10','猪骨汤','35/份','这个汤，非常鲜甜好喝，加了赤小豆和眉豆，还有祛湿的效果','汤类',1,'images/tanglei7.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('10','浓香雪耳汤','25/份','这个汤，非常鲜甜好喝，加了赤小豆和眉豆，还有祛湿的效果','汤类',1,'images/tanglei8.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('10','排骨玉米汤','35/份','这个汤，非常鲜甜好喝，加了赤小豆和眉豆，还有祛湿的效果','汤类',1,'images/tanglei9.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('10','鱼鳃益生汤','35/份','这个汤，非常鲜甜好喝，加了赤小豆和眉豆，还有祛湿的效果','汤类',1,'images/tanglei10.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('10','海带蛋花汤','20/份','这个汤，非常鲜甜好喝，加了赤小豆和眉豆，还有祛湿的效果','汤类',1,'images/tanglei11.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('10','凤爪红枣汤','25/份','这个汤，非常鲜甜好喝，加了赤小豆和眉豆，还有祛湿的效果','汤类',1,'images/tanglei12.png')

insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('16','清凉雪梨汁','13/杯','酸酸甜甜还有果粒的橘汁，既健康又经济','饮料',1,'images/yinliao4.png')
insert into dish_list(dish_id,dish_name,price,introduction,dish_class,img_download,img_path) values('16','特调鲜活雪碧','22/杯','酸酸甜甜还有果粒的橘汁，既健康又经济','饮料',1,'images/yinliao4.png')
